
name = "DashSocketio"
uuid = "1b08a953-4be3-4667-9a23-07d571ed62fd"
authors = ["Renaud Lain√© <>"]
version = "1.0.1"

[deps]
Dash = "1b08a953-4be3-4667-9a23-3db579824955"

[compat]
julia = "1.2"
Dash = "0.1.3, 1.0"
